language: java
sudo: required
services:
  - docker
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t razear/inventory-app -f Dockerfile.dev .
script:
  - mvn -DSPRING_PROFILES_ACTIVE=dev  test
  - mvn -DSPRING_PROFILES_ACTIVE=dev clean install