language: java
sudo: required
services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - COLLECT_ERROR= 1
before_install:
  - pip install fandogh-cli --upgrade
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - mvn -DSPRING_PROFILES_ACTIVE=dev install  -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t razear/inventory-app -f Dockerfile.dev .
script:
  - mvn -DSPRING_PROFILES_ACTIVE=dev  test
  - mvn -DSPRING_PROFILES_ACTIVE=dev clean install

after_success:
  - fandogh login --username $FANDOGH_USERNAME --password $FANDOGH_PASSWORD
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: main