language: java
sudo: required
services:
  - docker
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t razear/inventory-app -f Dockerfile.dev .
script:
<<<<<<< HEAD
<<<<<<< HEAD
#  - docker run -e CI=true razear/inventory-app mvn test -Bgit
=======
<<<<<<< HEAD
=======
>>>>>>> removing comments from tavis.yml
#  - docker run -e CI=true razear/inventory-app mvn test -B
#  - docker run -e CI=true razear/inventory-app mvn test -Bgit
<<<<<<< HEAD
>>>>>>> adding SaleInvoiceDto and SaleTransactionDto  closes #15 and fixing project errors
>>>>>>> adding SaleInvoiceDto and SaleTransactionDto  closes #15 and fixing project errors
=======

>>>>>>> removing comments from tavis.yml
  - mvn test
  - mvn clean install