language: java
sudo: required
services:
  - docker
before_install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - docker build -t razear/inventory-app -f Dockerfile.dev .
script:
<<<<<<< HEAD
#  - docker run -e CI=true razear/inventory-app mvn test -Bgit
=======
<<<<<<< HEAD
#  - docker run -e CI=true razear/inventory-app mvn test -B
=======
#  - docker run -e CI=true razear/inventory-app mvn test -Bgit
>>>>>>> adding SaleInvoiceDto and SaleTransactionDto  closes #15 and fixing project errors
>>>>>>> adding SaleInvoiceDto and SaleTransactionDto  closes #15 and fixing project errors
  - mvn test
  - mvn clean install