kind: ExternalService
name: mega-electric-app
spec:
  image:  razear/mega-electric-app:${SHA}
  port: 8080
  resources:
    memory: 500Mi
  volume_mounts:
    - mount_path: /files
      sub_path: spring-app
      volume_name: backend-files
