FROM amazoncorretto:11-alpine-jdk
COPY target/inventory-0.0.1-SNAPSHOT.jar inventory-app.jar
COPY files files

ARG ALLOWED_ORIGINS
ARG SPRING_PROFILES_ACTIVE
ARG JWT_TOKEN
ARG JWT_TOKEN_EXPIRE
ARG JWT_TOKEN_PREFIX
ARG MYSQL_USERNAME
ARG MYSQL_PASSWORD
ARG MYSQL_HOST
ARG MYSQL_DB_NAME

ENV ALLOWED_ORIGINS ${ALLOWED_ORIGINS}
ENV SPRING_PROFILES_ACTIVE ${SPRING_PROFILES_ACTIVE}
ENV JWT_TOKEN ${JWT_TOKEN}
ENV JWT_TOKEN_EXPIRE ${JWT_TOKEN_EXPIRE}
ENV JWT_TOKEN_PREFIX ${JWT_TOKEN_PREFIX}
ENV MYSQL_USERNAME ${MYSQL_USERNAME}
ENV MYSQL_PASSWORD ${MYSQL_PASSWORD}
ENV MYSQL_HOST ${MYSQL_HOST}
ENV MYSQL_DB_NAME ${MYSQL_DB_NAME}



ENTRYPOINT ["java", "-jar" , "/inventory-app.jar"]